#!/bin/bash

SRCDIR=./plugins

if [ -d $SRCDIR ]
then
  echo "----------------------------------------"
  echo "You've already got those plugins cloned!"
  echo "----------------------------------------"
  exit
fi

declare -a repos=(
                  "https://github.com/aptivate/ckanext-mapactiontheme.git"
                  "https://github.com/aptivate/ckanext-mapactionimporter.git"
                  "https://github.com/aptivate/ckanext-mapactionevent.git"
                  "https://github.com/aptivate/ckanext-mapactiongeorss.git"
                  "https://github.com/aptivate/ckanext-googleauth.git"
                  "https://github.com/aptivate/ckanext-userautoadd.git"
                  "https://github.com/aptivate/ckanext-datasetversions.git"
                  "https://github.com/aptivate/ckanext-datasetthumbnail.git"
                 )

mkdir -p $SRCDIR

echo "Cloning all Aptivate plugins into $SRCDIR ..."

for repo in "${repos[@]}"
do
  name=$(basename "$repo" .git)
  git clone "$repo" $SRCDIR/"$name"
done
